# Site settings
title: 笑笑     # 博客标题
SEOTitle: 笑笑 | BLOG     # 浏览器上显示的
header-img: images\Manipulation.jpg    # 背景图片 
description: 不可与夏虫语冰   # 网站介绍
keyword: keyword     # 关键字
url: 'https://zhao-xiaonan.github.io/' 
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Zhao Xiaonan'
  email: zhaoxiaonan724@gmail.com
  # twitter_username: Zhao-Xiaonan
  github_username:  Zhao-Xiaonan
  # linkedin_username:  Zhao-Xiaonan
  weibo_id: 2267020712
  jianshu_id: ce656da10d6c

# 侧边栏
sidebar: true
sidebar-about-description: "侧边栏描述"
sidebar-avatar: images\profile-zxn.jpg

# Build settings
destination: _site
gems: [jekyll-paginate]
paginate: 10
#paginate_path: "/blog/page:num"
permalink: /blog/:year/:month/:day/:title/
#permalink: "page:num"
markdown: kramdown
#highlighter: pygments
highlighter: pygments
excerpt_separator: "\n\n\n"

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
# theme: jekyll-theme-cayman
